---

- name: Creates new 'wp_prd' database 
  mysql_db:
    name: wp_db_prd
    state: present
  when: ansible_facts['distribution'] == "CentOS"
  
- name: Creates database, password, database privileges 'WITH GRANT OPTION'
  mysql_user:
    name: wp_user_01
    password: "{{ dbpass }}"
    priv: 'wp_db_prd.*:ALL,GRANT'
    host: "%"
    state: present
  when: ansible_facts['distribution'] == "CentOS"